/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Marketing and SEO pages for sterio.fm.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path segment, e.g. "home", "about", or "guides/find-producer".
   */
  slug: string;
  status: 'draft' | 'published';
  seo?: {
    /**
     * Browser tab and search result title. Falls back to page title.
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Absolute URL or site path (e.g. /marketing/duke-pfp.jpg).
     */
    ogImage?: string | null;
    ogImageAlt?: string | null;
    noIndex?: boolean | null;
    /**
     * Optional JSON-LD object or array for schema.org markup.
     */
    structuredData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  layout: (
    | {
        eyebrow?: string | null;
        headline: string;
        subhead?: string | null;
        actions?:
          | {
              label: string;
              /**
               * Relative path (e.g. /register) or full URL.
               */
              href: string;
              variant?: ('primary' | 'secondary') | null;
              id?: string | null;
            }[]
          | null;
        stats?:
          | {
              highlight: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        showPhoneMock?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        subhead?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pageHero';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        leftTitle: string;
        leftText: string;
        rightTitle: string;
        rightText: string;
        rightStyle?: ('default' | 'gradient') | null;
        softBackground?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'twoPanel';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        subhead?: string | null;
        anchorId?: string | null;
        softBackground?: boolean | null;
        steps: {
          number: string;
          title: string;
          text: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'steps';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        subhead?: string | null;
        features: {
          icon?: string | null;
          title: string;
          text: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'featureCards';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        text: string;
        quote: string;
        quoteAttribution?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'community';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        text?: string | null;
        buttonLabel: string;
        buttonHref: string;
        anchorId?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        image: string;
        imageAlt: string;
        eyebrow?: string | null;
        heading: string;
        paragraphs: {
          text: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'story';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        variant: 'beliefs' | 'team' | 'guides' | 'downloads';
        softBackground?: boolean | null;
        cards: {
          meta?: string | null;
          title: string;
          text?: string | null;
          image?: string | null;
          imageAlt?: string | null;
          role?: string | null;
          href?: string | null;
          linkLabel?: string | null;
          platform?: string | null;
          featured?: boolean | null;
          buttonLabel?: string | null;
          buttonHref?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'cardGrid';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        subhead?: string | null;
        actions?:
          | {
              label: string;
              /**
               * Relative path (e.g. /register) or full URL.
               */
              href: string;
              variant?: ('primary' | 'secondary') | null;
              id?: string | null;
            }[]
          | null;
        image: string;
        imageAlt: string;
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pluginHero';
      }
    | {
        backHref?: string | null;
        backLabel?: string | null;
        meta?: string | null;
        headline: string;
        intro?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'articleHeader';
      }
    | {
        sections: {
          type: 'heading' | 'paragraph' | 'callout' | 'html';
          heading?: string | null;
          text?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          /**
           * Paste trusted embed HTML (charts, iframes, etc.). Only use code from sources you trust.
           */
          html?: string | null;
          /**
           * Optional caption shown below the embed.
           */
          caption?: string | null;
          buttonLabel?: string | null;
          buttonHref?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'articleSections';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        text?: string | null;
        anchorId?: string | null;
        actions?:
          | {
              label: string;
              /**
               * Relative path (e.g. /register) or full URL.
               */
              href: string;
              variant?: ('primary' | 'secondary') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'centeredActions';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        ogImageAlt?: T;
        noIndex?: T;
        structuredData?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subhead?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              stats?:
                | T
                | {
                    highlight?: T;
                    label?: T;
                    id?: T;
                  };
              showPhoneMock?: T;
              id?: T;
              blockName?: T;
            };
        pageHero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subhead?: T;
              id?: T;
              blockName?: T;
            };
        twoPanel?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              leftTitle?: T;
              leftText?: T;
              rightTitle?: T;
              rightText?: T;
              rightStyle?: T;
              softBackground?: T;
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subhead?: T;
              anchorId?: T;
              softBackground?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featureCards?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subhead?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        community?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              text?: T;
              quote?: T;
              quoteAttribution?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              text?: T;
              buttonLabel?: T;
              buttonHref?: T;
              anchorId?: T;
              id?: T;
              blockName?: T;
            };
        story?:
          | T
          | {
              image?: T;
              imageAlt?: T;
              eyebrow?: T;
              heading?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              variant?: T;
              softBackground?: T;
              cards?:
                | T
                | {
                    meta?: T;
                    title?: T;
                    text?: T;
                    image?: T;
                    imageAlt?: T;
                    role?: T;
                    href?: T;
                    linkLabel?: T;
                    platform?: T;
                    featured?: T;
                    buttonLabel?: T;
                    buttonHref?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pluginHero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subhead?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              image?: T;
              imageAlt?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        articleHeader?:
          | T
          | {
              backHref?: T;
              backLabel?: T;
              meta?: T;
              headline?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
        articleSections?:
          | T
          | {
              sections?:
                | T
                | {
                    type?: T;
                    heading?: T;
                    text?: T;
                    html?: T;
                    caption?: T;
                    buttonLabel?: T;
                    buttonHref?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        centeredActions?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              text?: T;
              anchorId?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HtmlSnippetBlock".
 */
export interface HtmlSnippetBlock {
  /**
   * Paste trusted embed HTML (charts, iframes, scripts from known providers). Only use code from sources you trust.
   */
  html: string;
  /**
   * Optional caption shown below the embed.
   */
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'htmlSnippet';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}